CREATE TABLE IF NOT EXISTS applications (
		id SERIAL PRIMARY KEY,
		company VARCHAR(255) NOT NULL,
		position VARCHAR(255) NOT NULL,
		status VARCHAR(255) NOT NULL,
		created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
	);
